version: '3.4'

services:
  project-backend:
    image: r0618721/project-backend
#     build:
#       context: .
#       dockerfile: /Dockerfile
    ports:
      - "80:80"
    depends_on:
          - Utopia

  Utopia:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
#     user: SA
    ports:
      - 1433:1433  
    environment:
        SA_PASSWORD: "Utopia2.0"
        ACCEPT_EULA: "Y"
    volumes:
      - sqldata:/var/opt/mssql
volumes:
  sqldata:
